let timelineElements = [
    {
        id: 1,
        title: "Nitrogen Generator System Project (SGN)",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        laboratory: "Laboratory of Heat Transfer and Technology (LTTC), PEM/COPPE/UFRJ",
        coordinator: "Helcio Rangel Barreto Orlande, COPPE/UFRJ",
        latermoMember: "Cesar Cunha Pacheco",
        teamMembers: "Marcelo José Colaço, Albino José Kalab Leiroz, Diego Cardoso Estumano",
        description: "Develop a computer program to calculate the temperature field in a pipeline containing paraffin blockage, under the action of the SGN thermochemical technique",
        abstract: "This project aims to develop a computer program for calculating the temperature field in a duct containing paraffin blockage, under the action of the SGN (Nitrogen Generation System) thermochemical technique. The primary result of this computer program will be an estimate of the maximum temperatures reached in the various layers of the duct wall during the paraffin liquefaction process and subsequent duct unclogging.",
        deliverables: ["Computer program for estimating the maximum temperatures reached in the various layers of the pipe wall during the paraffin wax liquefaction process and subsequent pipe unclogging"],
        trl: 2,
        company: "Petrobras",
        buttonText: "View Details",
        date: "2013-2014",
        icon: "logo_petrobras",
    },
    {
        id: 2,
        title: "Laboratory of Heat Transfer Measurements in Ducts under Hyperbaric Conditions",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        laboratory: "Laboratory of Heat Transfer and Technology (LTTC), PEM/COPPE/UFRJ",
        coordinator: "Marcelo José Colaço, COPPE/UFRJ",
        latermoMember: "Cesar Cunha Pacheco, Kleber Marques Lisboa",
        teamMembers: "Marcelo José Colaço, Renato Machado Cotta, Helcio Rangel Barreto Orlande, Sylvio José Ribeiro de Oliveira, Wilson S.V. Maior",
        description: "Development of a new experimental facility to study heat transfer in ducts under hyperbaric conditions",
        abstract: "This project aims to develop a project for the construction of a laboratory for determining overall heat transfer coefficients in ducts under hyperbaric conditions, in accordance with applicable standards.",
        deliverables: ["Design of a laboratory for the determination of overall heat transfer coefficients in pipes under hyperbaric conditions, in accordance with applicable standards"],
        trl: 2,
        company: "Tenaris",
        buttonText: "View Details",
        date: "2014-2014",
        icon: "logo_tenaris",
    },
    {
        id: 3,
        title: "Thermohydraulic Analysis of Prototype of the Irradiated Fuel Storage Unit of CNAAA",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        laboratory: "Laboratory of Heat Transfer and Technology (LTTC), PEM/COPPE/UFRJ",
        coordinator: "Su Jian, COPPE/UFRJ",
        latermoMember: "Kleber Marques Lisboa",
        teamMembers: "Renato Machado Cotta, Su Jian, Helcio Rangel Barreto Orlande, Marcelo Colaço, Larissa Cunha Pinheiro",
        description: "Development of passive systems for the removal of residual heat from pools of spent nuclear fuel",
        abstract: "Due to the depletion of spent fuel storage capacity in the spent fuel pools of Angra 1 and 2 nuclear power plants, Eletronuclear's spent fuel management policy foresees the implementation of a complementary facility to allow for the storage of spent fuel assemblies (SFAs) throughout the plants' 60-year lifespan. This Complementary Spent Fuel Storage Unit ensures storage until 2040, regardless of the implementation of the Long-Term Intermediate Storage Repository (under the responsibility of CNEN). Eletronuclear's proposed solution involves storing SFAs in wet storage tanks similar to those in the Spent Fuel Pools of Angra 1, 2, and 3 nuclear power plants. This choice is based on the successful use of similar facilities in numerous nuclear power plants. To experimentally simulate and test components of the passive cooling system, a prototype of the same must be constructed. The main objective of this project is to develop a computational simulation tool for the prototype of this cooling system, which will be designed and constructed in the future. The computational simulation tool will involve numerical analyses of the various phenomena occurring in this system, including, among others, natural convection in the tank containing the heat source, in the tubes, and in the chimney, as well as heat transfer between the hot and cold fluids in the water-water and water-air heat exchangers. This computational tool will allow for the future analysis, through the performance of new numerical simulations of the subsystems described below, of new proposals for tanks, chimneys, or heat exchangers.",
        deliverables: ["Design of single-phase thermosiphons for passive heat removal from spent fuel pools using natural convection"],
        trl: 2,
        company: "Eletronuclear",
        buttonText: "View Details",
        date: "2015-2016",
        icon: "logo_eletronuclear",
    },
    {
        id: 4,
        title: "Computational Simulation of Magnetohydrodynamic Flows for Applications in the Oil Industry",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        laboratory: "Heat Engines Laboratory (LMT), PEM/COPPE/UFRJ",
        coordinator: "Marcelo José Colaço, COPPE/UFRJ",
        latermoMember: "Cesar Cunha Pacheco",
        teamMembers: "Marcelo José Colaço, Albino José Kalab Leiroz, Manuel Ernani de Carvalho Cruz, Gabriel Lisbôa Veríssimo",
        description: "Analysis and computational simulation of various models of magnetohydrodynamic flows relevant to the oil industry",
        abstract: "The project aims to analyze and computationally simulate various magnetohydrodynamic flow models, with the objective of presenting technical solutions for typical problems in the petroleum industry.",
        deliverables: [""],
        trl: 3,
        company: "Petrobras",
        buttonText: "View Details",
        date: "2016-2017",
        icon: "logo_petrobras",
    },
    {
        id: 5,
        title: "Theoretical-Experimental Analysis of Heat Transfer in Flare Structures - TRL4",
        location: "Fluminense Federal University (UFF)",
        laboratory: "Laboratory of Thermal Sciences (Latermo), TEM/PGMEC/UFF",
        coordinator: "Leandro Alcoforado Sphaier, UFF",
        latermoMember: "Cesar Cunha Pacheco, Isabela Florindo Pinheiro, Kleber Marques Lisboa, Leandro Alcoforado Sphaier",
        teamMembers: "Fabio Toshio Kanizawa, Jaqueline Diniz da Silva, Robson Felipe Viana da Silva, Luiz Cesar Coutinho Junior",
        description: "Develop thermal shields for protection against radiation incident upon polymer repairs in flare structure pipelines",
        abstract: "This project encompasses the development of a thermal insulation system for polymeric repairs made on the metallic structures of flare stacks, commonly found in oil and gas production and refining plants. These repairs must operate at temperatures below 200°C; however, this is not possible if they are exposed to the thermal radiation emitted by the flare flame. Thus, it is proposed to evaluate a thermal insulation system in order to mitigate the heating caused by the flame radiation. To specify the insulation system, the conjugated conduction-radiation heat transfer in the structure will be primarily considered. However, since the installation of the insulation system alters the airflow around the structure, there may be a significant change in the heat transfer by convection with the air, and this phenomenon will also be analyzed. To complete the specification of a thermal insulation system, in addition to its thermal design, the mechanical design will also be carried out, considering the structural analysis of the proposed insulation system. Finally, in addition to the insulation system, situations with and without the proposed system will be analyzed to demonstrate its effectiveness.",
        deliverables: ["Design and laboratory-scale validation of shielding for protection against radiation from polymeric repairs for flare structures", "Computational simulation to characterize the shielding performance in a relevant environment"],
        trl: 4,
        company: "Petrobras",
        buttonText: "View Details",
        date: "2019-2023",
        icon: "logo_petrobras",
    },
    {
        id: 6,
        title: "Microchannels-based Heat Sinks for Waste Heat Recovery from High Concentration Photovoltaic Cells and Reuse for Desalination",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        laboratory: "Laboratory of Nano and Microfluidics and Microsystems (LabMEMS), PEM/COPPE/UFRJ",
        coordinator: "Carolina Palma Naveira-Cotta, COPPE/UFRJ",
        latermoMember: "Kleber Marques Lisboa",
        teamMembers: "Carolina Palma Naveira-Cotta, Renato Machado Cotta, Abdul Orlando Cárdenas Gómez, Luz Elena Peñaranda Chenche, Ingrid Vasconcelos Curcino, Bruno Scaramuzza dos Reis, Eduardo Santos Paiva, Rafael San Martin, Emerson Barbosa dos Anjos",
        description: "Develop heat sinks for the recovery of waste heat from high concentration photovoltaic (HCPV) panels with co-generation of potable water",
        abstract: "The United Nations' Sustainable Development Goals have stimulated research and technological advancements in recent years, particularly within the field of thermal engineering, focusing on the recovery of high and low-grade waste heat from power generation and general process industries for secondary processes aligned with these goals. Moreover, advancements in nano and micro-technologies have enabled significant efficiency improvements in heat and mass transfer processes, which under certain economic conditions and environmental conservation incentives, can lead to innovations for applications in this context. The proposed research focuses on integrating High Concentration Photovoltaics (HCPV) electrical conversion systems with active cooling systems based on microchannels and recovering this waste heat for water desalination, opening up prospects for the use of this sustainable system in remote regions where there is a demand for energy, water, or both simultaneously, such as offshore oil platforms, thus demonstrating a positive impact and contributing technologically to a holistic approach to addressing the complex challenges of food, water, energy, and environmental conservation. Therefore, this research and development project proposal aims to demonstrate, in a relevant environment, the differences in the electrical conversion efficiency of high-concentration photovoltaic panels when using an active microchannel cooling system based on single-phase forced convection of common fluids (water), as well as the modeling and experimental analysis of direct contact membrane distillation (DCMD) processes for water desalination using waste heat recovered from solar panels. This proposal will be developed at the Nano and Microfluidics and Microsystems LabMEMS Laboratory at COPPE/UFRJ. This laboratory has benefited from collaborations with the Instituto Superior Tecnico de Lisboa-IST (Lisbon, Portugal), the Nanosystems Engineering Laboratory at University College London-UCL (London, United Kingdom), and the Center for Environmental Energy Engineering at the University of Maryland (College Park, United States). All of these are world-renowned universities with recognized technical capabilities in intensifying heat and mass transfer processes due to their laboratory facilities, equipment, and specialties that have been developed over the past few years of research.",
        deliverables: ["Design and implementation of a prototype in a relevant environment for heat recovery from HCPV panels and reuse for water desalination", "Characterization of the polygeneration plant for electricity and potable water", "Software for analysis and system design of polygeneration plants for electricity and potable water"],
        trl: 6,
        company: "Petrogal Brasil via ANP and EMBRAPII",
        buttonText: "View Details",
        date: "2020-2024",
        icon: "logo_galp",
    },
    {
        id: 7,
        title: "EnerGente Project: Development of a Distributed Sustainable System for the Polygeneration of Electricity, Potable Water, and Green Hydrogen",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        laboratory: "Laboratory of Nano and Microfluidics and Microsystems (LabMEMS), PEM/COPPE/UFRJ",
        coordinator: "Carolina Palma Naveira-Cotta, COPPE/UFRJ",
        latermoMember: "Kleber Marques Lisboa",
        teamMembers: "Carolina Palma Naveira-Cotta, Renato Machado Cotta, Abdul Orlando Cárdenas Gómez, Luz Elena Peñaranda Chenche, Ingrid Vasconcelos Curcino, Bruno Scaramuzza dos Reis, Daniel Rubano Barretto Turci, Rafael San Martin, Emerson Barbosa dos Anjos",
        description: "Develop a prototype of a plant for the polygeneration of photovoltaic electricity, potable water, and green hydrogen",
        abstract: "The United Nations' Sustainable Development Goals have stimulated research and technological advancements in recent years, particularly within the thermal engineering field, focusing on the recovery of high and low-grade waste heat from power generation and general process industries for secondary processes aligned with these goals. The utilization of low-grade waste heat, characteristically involving reduced temperature differences, can greatly benefit from the intensification of transport phenomena promoted by miniaturization achieved through advances in micro and nanotechnologies, increasing interest in innovations in this direction. This research focuses on the integration of power generation processes (through photovoltaic, solar thermal, and engine-generator systems) for use in sustainable cogeneration processes, utilizing recovered waste heat, supplemented by heat recovered from solar collectors, to produce various essential inputs such as: desalinated water obtained through membrane distillation and reverse osmosis; electricity generation from salinity gradients using high salinity water (waste from the desalination process); and green hydrogen generation from the electrolysis of distilled water produced. The demonstration and integration of these equipment and technological solutions will occur at three different levels: relevant environment (TRL6) and laboratory environment (TRL4), and as opportunities arise and the performance of the processes is proven, they will be progressively incorporated into higher TRLs. The research aligns with ANP's technology policy, which supports innovative solutions in the biofuels, renewable energy, energy transition, and decarbonization sectors, opening up prospects for the use of these sustainable technologies in remote regions and their modular and transportable nature will allow for meeting supply demands in different scenarios, contributing technologically to a holistic approach to addressing the complex challenges of the water-energy-food-ecosystem nexus, considering the interdependence of these elements essential to life and environmental preservation, and being present in 14 of the 17 UN Sustainable Development Goals. It also incorporates important components of the circular economy and waste valorization, offering an avenue of opportunities for future expansions in the supply of other inputs and incorporation of new technologies, among which the present project addresses: electricity generation (via photovoltaic panels and engine-generator) with heat recovery for the conduction of water distillation processes and green hydrogen production.",
        deliverables: ["Design and implementation of a prototype in a relevant environment of photovoltaic-thermal panels for electricity generation with cogeneration of potable water and green hydrogen storage", "Design and implementation of a bench-scale prototype (TRL4) of a salinity gradient power generation system", "Characterization of the polygeneration plant for electricity, potable water, and green hydrogen", "Software for analysis and system design of polygeneration plants for electricity, potable water, and green hydrogen"],
        trl: 6,
        company: "Petrogal Brasil via ANP",
        buttonText: "View Details",
        date: "2024-present",
        icon: "logo_galp",
    },
    {
        id: 8,
        title: "Treatment of Hypersaline Produced Water via the Membrane Distillation Process",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        laboratory: "Laboratory of Nano and Microfluidics and Microsystems (LabMEMS), PEM/COPPE/UFRJ",
        coordinator: "Carolina Palma Naveira-Cotta, COPPE/UFRJ",
        latermoMember: "Kleber Marques Lisboa",
        teamMembers: "Carolina Palma Naveira-Cotta, Renato Machado Cotta, Marcelo José Colaço, Abdul Orlando Cárdenas Gómez, Carlos Reuther, Pedro Reuther, Krishina Dasa Alves da Costa, Luelen Barbosa",
        description: "Develop a system for the recovery of waste heat from gas turbines for the treatment of formation and produced water from oil & gas wells using membrane distillation",
        abstract: "The contaminants present in produced water (PW) vary according to well location and exploration techniques employed. However, regulations on contaminant levels and dissolved salts are becoming increasingly stringent, creating a need for effective, compact, modular, and preferably low-cost techniques for treating these effluents. Additionally, the oil and gas industry is committed to decarbonizing its production operations. These facts open up opportunities for the reuse of produced water after adequate treatment. However, excessive salinity, often exceeding 150 g/L of dissolved salts, hinders the use of reverse osmosis (RO), opening up space for distillation processes such as membrane distillation. This project aims to demonstrate the use of low-grade waste heat, which is generally discarded into the environment, as an energy input for the membrane distillation of produced water. To this end, real-world scenarios of interest to partner operators will be identified for the application of the proposed solution. The research group will develop an experimentally validated numerical model that will allow for a systematic analysis of these real-world scenarios. In the validation effort, experiments will be conducted using hypersaline produced water mimicked with solutions of TDS varying from 30 g/L to 200 g/L. These experiments will be conducted in a TRL6 membrane distillation demonstration prototype that will utilize the low-grade waste heat from the exhaust gases of microturbines. Additionally, a bench-scale laboratory experimental analysis (TRL4) will be conducted using real produced water (PW) samples, provided by partner operators, in order to allow a detailed analysis of fouling/scaling effects on different commercial membranes under different operating conditions and pretreatment procedures.",
        deliverables: ["Design and implementation of a relevant environment prototype (TRL6) of a gas microturbine with waste heat recovery for hypersaline water treatment", "Design and implementation of a bench-scale prototype (TRL4) of an oilfield produced water treatment system", "Characterization of the hypersaline water treatment plant using gas turbine waste heat", "Software for analysis and system design of hypersaline water treatment plants using gas turbine waste heat"],
        trl: 6,
        company: "TotalEnergies and QatarEnergy via ANP",
        buttonText: "View Details",
        date: "2024-present",
        icon: "logo_total",
    }
]

export default timelineElements;