let timelineElements = [
    {
        id: 1,
        title: "Nitrogen Generator System Project (SGN)",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        description: "Develop a computer program to calculate the temperature field in a pipeline containing paraffin blockage, under the action of the SGN thermochemical technique",
        trl: 2,
        company: "Petrobras",
        buttonText: "View Details",
        date: "2013-2014",
        icon: "logo_petrobras",
    },
    {
        id: 2,
        title: "Laboratory of Heat Transfer Measurements in Ducts under Hyperbaric Conditions",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        description: "Development of a new experimental facility to study heat transfer in ducts under hyperbaric conditions",
        trl: 2,
        company: "Tenaris",
        buttonText: "View Details",
        date: "2014-2014",
        icon: "logo_tenaris",
    },
    {
        id: 3,
        title: "Thermohydraulic Analysis of Prototype of the Complementary Irradiated Fuel Storage Unit of CNAAA",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        description: "Development of passive systems for the removal of residual heat from pools of spent nuclear fuel",
        trl: 2,
        company: "Eletronuclear",
        buttonText: "View Details",
        date: "2015-2016",
        icon: "logo_eletronuclear",
    },
    {
        id: 4,
        title: "Computational Simulation of Magnetohydrodynamic Flows for Applications in the Oil Industry",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        description: "Analysis and computational simulation of various models of magnetohydrodynamic flows relevant to the oil industry",
        trl: 3,
        company: "Petrobras",
        buttonText: "View Details",
        date: "2016-2017",
        icon: "logo_petrobras",
    },
    {
        id: 5,
        title: "Theoretical-Experimental Analysis of Heat Transfer in Flare Structures - TRL4",
        location: "Fluminense Federal University (UFF)",
        description: "Develop thermal shields for protection against radiation incident upon polymer repairs in flare structure pipelines",
        trl: 4,
        company: "Petrobras",
        buttonText: "View Details",
        date: "2019-2023",
        icon: "logo_petrobras",
    },
    {
        id: 6,
        title: "Microchannels-based Heat Sinks for Waste Heat Recovery from High Concentration Photovoltaic Cells and Reuse for Desalination",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        description: "Develop heat sinks for the recovery of waste heat from high concentration photovoltaic (HCPV) panels with co-generation of potable water",
        trl: 6,
        company: "GALP",
        buttonText: "View Details",
        date: "2020-2024",
        icon: "logo_galp",
    },
    {
        id: 7,
        title: "EnerGente Project: Development of a Distributed Sustainable Polygeneration System of Electricity, Potable Water, and Green Hydrogen",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        description: "Develop a prototype of a polygeneration plant for photovoltaic electricity, potable water, and green hydrogen",
        trl: 6,
        company: "GALP",
        buttonText: "View Details",
        date: "2024-present",
        icon: "logo_galp",
    },
    {
        id: 8,
        title: "Treatment of Hypersaline Produced Water via the Membrane Distillation Process",
        location: "Federal University of Rio de Janeiro (UFRJ)",
        description: "Develop a system for the recovery of waste heat from gas turbines for the treatment of formation water and oil production using membrane distillation",
        trl: 6,
        company: "TotalEnergies and QatarEnergy",
        buttonText: "View Details",
        date: "2024-present",
        icon: "logo_total",
    }
]

export default timelineElements;